[package]
name = "swaynyaad"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = "1.0.202"
serde_json = "1.0.117"
smol = "2.0.0"
swayipc-async = { path = "../swayipc-rs/async" }
