[package]
name = "swaynyaad"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
futures-lite = "2.3.0"
serde = "1.0.202"
serde_json = "1.0.117"
swayipc-async = { path = "../swayipc-rs/async" }
tokio = { version = "1.39.3", default-features = false, features = ["rt", "macros", "process"] }

